# -*- coding: utf-8 -*-
"""pulsar2 parabola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9SZNivLO-rqmrpNi1sHvabUM6vHYW_5
"""

import pandas as pd
from google.colab import files
data_to_load = files.upload()

import io
df = pd.read_csv(io.BytesIO(data_to_load['pulsar2.csv']))
import numpy as np
x=df['time']
y=df['y']
yerr=df['yerr']

def model(x, m, p,c):
    return m*x**2 + p*x + c

!pip install bilby
import bilby
likelihood = bilby.likelihood.GaussianLikelihood(x, y, model, yerr)

priors = dict()
priors["m"] = bilby.core.prior.Uniform(-10**-6, -10**-8, "m")
priors["p"] = bilby.core.prior.Uniform(10**-3, 10**-1, "p")
priors["c"] = bilby.core.prior.Uniform(-10**4,-10**2 ,"c")

injection_parameters = dict(m=-2.81720693e-07, p= 3.32839855e-02, c=-9.83063769e+02)
label = "linear_regression_2"
outdir2 = "outdir2"
bilby.utils.check_directory_exists_and_if_not_mkdir(outdir2)


result = bilby.run_sampler(
    likelihood=likelihood,
    priors=priors,
    sampler="dynesty",
    nlive=250,
    injection_parameters=injection_parameters,
    resume=False,
    outdir2=outdir2,
    label=label,
)

# Finally plot a corner plot: all outputs are stored in outdir
result.plot_corner()

