# -*- coding: utf-8 -*-
"""pulsar1_parabola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wV69JYT7jKShSnSJJgaz0VWubdPH2a6E
"""

!pip install bilby

import bilby
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd
from google.colab import files
data_to_load = files.upload()

import io
df = pd.read_csv(io.BytesIO(data_to_load['pulsar.csv']))
import numpy as np
x=df['time']
y=df['y']
yerr=df['error']

def model(x, m, p,c):
    return m*x**2 + p*x + c

likelihood = bilby.likelihood.GaussianLikelihood(x, y, model, yerr)

priors = dict()
priors["m"] = bilby.core.prior.Uniform(-0.1, 0, "m")
priors["p"] = bilby.core.prior.Uniform(10, 10**3, "p")
priors["c"] = bilby.core.prior.Uniform(-10**8, -10**5, "c")

injection_parameters = dict(m=-3.59694146e-03, p=4.18750871e+02, c=-1.21863397e+07)
label = "linear_regression"
outdir1 = "outdir1"
bilby.utils.check_directory_exists_and_if_not_mkdir(outdir1)


result = bilby.run_sampler(
    likelihood=likelihood,
    priors=priors,
    sampler="dynesty",
    nlive=250,
    injection_parameters=injection_parameters,
    resume=False,
    outdir=outdir1,
    label=label,
)

# Finally plot a corner plot: all outputs are stored in outdir
result.plot_corner()

