# -*- coding: utf-8 -*-
"""pulsar1_line.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZaf5um7OWeZAXEbXa0DOrn1AUNchcZy
"""

!pip install bilby

import bilby
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd
from google.colab import files
data_to_load = files.upload()

import io
df = pd.read_csv(io.BytesIO(data_to_load['pulsar.csv']))
import numpy as np
x=df['time']
y=df['TOTAL']
t=df['y']
yerr=df['error']

def model_array(x, m, p,c,d):
    model_array=[]
    for i in x:
      if(i<=58595.52815):
        model = m*i + p
        model_array.append(model)
      else:
        model= c*i + d
        model_array.append(model)
    model_array= np.array(model_array) 
    return model_array

import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

model_array1=-4.94640729e-01*x + 2.99287267e+04

likelihood = bilby.likelihood.GaussianLikelihood(x, y, model_array, yerr)

priors = dict()
priors["m"] = bilby.core.prior.Uniform(-10, 10, "m")
priors["p"] = bilby.core.prior.Uniform(10**2, 10**7, "p")
priors["c"] = bilby.core.prior.Uniform(-30, 20, "c")
priors["d"] = bilby.core.prior.Uniform(10**2, 10**9, "d")

injection_parameters = dict(m=-4.94640643e-01, p=2.99287217e+04, c=-8.16287993e+00, d=4.80878880e+05)
label = "linear_regression"
outdir1 = "outdir4"
bilby.utils.check_directory_exists_and_if_not_mkdir(outdir1)


result = bilby.run_sampler(
    likelihood=likelihood,
    priors=priors,
    sampler="dynesty",
    nlive=250,
    injection_parameters=injection_parameters,
    outdir=outdir1,
    label=label,
)

# Finally plot a corner plot: all outputs are stored in outdir
result.plot_corner()